export const FilterFlags = {
  FLAGS: {
    PINNED: "pinned",
    NOT_PINNED: "not_pinned",
    REGEX: "regex",
    NOT_REGEX: "not_regex",
    ALL: "all",
    WITH_LINK: "with_link",
    WITHOUT_LINK: "without_link",
    WITH_EMOJIS: "with_emojis",
    WITHOUT_EMOJIS: "without_emojis",
    WITH_ATTACHMENT: "with_attachment",
    WITHOUT_ATTACHMENT: "without_attachment",
    USAGE_ALL: "all",
    USAGE_ONE: "one",
  },
  IDS: {
    PINNED: 7,
    NOT_PINNED: 8,
    REGEX: 9,
    NOT_REGEX: 10,
    ALL: 0,
    WITH_LINK: 3,
    WITHOUT_LINK: 4,
    WITH_EMOJIS: 1,
    WITHOUT_EMOJIS: 2,
    WITH_ATTACHMENT: 5,
    WITHOUT_ATTACHMENT: 6,
  },
};
